
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const PASS_RESET = 'PASS_RESET'
export const PASS_RESET_SUCCESS = 'PASS_RESET_SUCCESS'
export const PASS_RESET_FAIL = 'PASS_RESET_FAIL'

export const POST_EXCHANGE = 'POST_EXCHANGE'